---
# .kitchen.yml:  Test Kitchen configuration file.
driver:
  name: docker
  use_sudo: false

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
      # run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - apt-get update && apt-get -y upgrade
        - apt-get install -y python-pip rsyslog
        - pip install ansible==2.4.2.0
        - sed -i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
        - sed -i 's/#LogLevel INFO/LogLevel DEBUG/g' /etc/ssh/sshd_config
        - systemctl enable rsyslog.service
        # - systemctl enable sshd.service

provisioner:
  ansible_inventory: inventories/kitchen
  ansible_verbose: false
  ansible_verbosity: 3
  hosts: all
  idempotency_test: true
  name: ansible_playbook
  require_ansible_repo: false
  require_chef_for_busser: false
  require_chef_omnibus: false
  require_pip: false

verifier:
  name: serverspec
  sudo_path: true

suites:
  - name: ubuntu-sandbox
    verifier:
      patterns:
        - spec/*_spec.rb
    provisioner:
      playbook: apache.yml
    driver_config:
      hostname: ubuntu-sandbox.local
      instance_name: ubuntu-sandbox
